// User
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";
export const SET_USER_DISPLAYNAME = "SET_USER_DISPLAYNAME";
export const SET_USER_STORIES = 'SET_USER_STORIES';
export const SET_PUBLIC_STORIES = 'SET_PUBLIC_STORIES';

// Display
export const SET_IS_SHOWING_SIGNIN_DIALOG = "SET_IS_SHOWING_SIGNIN_DIALOG";
