// User
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_USER_DISPLAYNAME = 'SET_USER_DISPLAYNAME';

// Users
export const SET_USERS = 'SET_USERS';

// User Stories
export const SET_USER_STORIES = 'SET_USER_STORIES';
export const REMOVE_USER_STORY = 'REMOVE_USER_STORY';

// Public Stories
export const SET_PUBLIC_STORIES = 'SET_PUBLIC_STORIES';
export const REMOVE_PUBLIC_STORY = 'REMOVE_PUBLIC_STORY';

// Display
export const SET_IS_SHOWING_SIGNIN_DIALOG = 'SET_IS_SHOWING_SIGNIN_DIALOG';
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

// Navigation
export const SET_OPENED_PREVIEW_FROM_APPLICATION = 'SET_OPENED_PREVIEW_FROM_APPLICATION';

// Story
export const SET_STORY = 'SET_STORY';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const ADD_HOTSPOT = 'ADD_HOTSPOT';
export const ADD_DOOR = 'ADD_DOOR';
export const ADD_ROOM = 'ADD_ROOM';
export const SET_HOTSPOT_LOCATION = 'SET_HOTSPOT_LOCATION';
export const SET_STORY_NAME = 'SET_STORY_NAME';
export const SET_STORY_TAGS = 'SET_STORY_TAGS';
export const SET_STORY_SOUNDTRACK = 'SET_STORY_SOUNDTRACK';
export const SET_PROJECT = 'SET_PROJECT';
export const UPDATE_DOOR = 'UPDATE_DOOR';
export const SET_ROOM_NAME = 'SET_ROOM_NAME';
export const SET_ROOM_BACKGROUND = 'SET_ROOM_BACKGROUND';
export const SET_HOTSPOT_NAME = 'SET_HOTSPOT_NAME';
export const SET_HOTSPOT_TEXT = 'SET_HOTSPOT_TEXT';
export const SET_HOTSPOT_IMAGE = 'SET_HOTSPOT_IMAGE';
export const SET_HOTSPOT_AUDIO = 'SET_HOTSPOT_AUDIO';
export const SET_ROOM_BACKGROUND_MUSIC = 'SET_ROOM_BACKGROUND_MUSIC';
export const SET_ROOM_BACKGROUND_NARRATION = 'SET_ROOM_BACKGROUND_NARRATION';
export const SET_ROOM_IS_HOME = 'SET_ROOM_IS_HOME';
